apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5-uda
  labels:
    app: project5-uda
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: project5-uda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project5-uda
    spec:
      containers:
        - image: src1307/myproject:v1
          imagePullPolicy: Always
          name: newimage
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project5-uda
  labels:
    app: project5-uda
spec:
  type: LoadBalancer
  selector:
    app: project5-uda
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
