version: 2.1
jobs:
  test-phase:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  build-docker:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build docker image
          command: |
            docker build --tag=myimage .
            docker image ls
  upload_image:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: upload docker image
          command: |
            echo "Docker image name is : $DOCKER_IMAGE"
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWD"
            docker tag myimage $DOCKER_CUSTOM_IMAGE
            docker push $DOCKER_CUSTOM_IMAGE
            

workflows:
  default:
      jobs:
        - test-phase  
        - build-docker:
            requires: [test-phase]
        - upload_image:
            requires: [build-docker]
